# Site settings
name: Hillarus
title: Hillarus
#email: your-email@domain.com
description: "Hillarus' Blog"
baseurl: ""
url: "http://www.hillarus.com"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html
